### ISSUE TITLE
Mensaje error 

### ISSUE THREAD

**Issue by VirginiaGomezR** [Adalab/Project-PromoJ-Modulo-2-Team-5#9]
Añadir una clase que valide cuando falte algun campo al hacer click en sección comparte

**Comment by Sonia-SV** [comment]
Solucionado añadiendo las funciones que hizo @VirginiaGomezR a una nueva función que es escuchada por el título de la sección comparte. Faltaría añadir un mensaje para la foto siempre y cuando no se use la nuestra por defecto si la usuaria no sube ninguna. Primero habría que decidir esto. Subida a la rama Ticket#9
